package model;


public record ContactData
        (String id,
         String first_name,
         String middle_name,
         String last_name,
         String nickname,
         String photo,
         String title,
         String company,
         String address,
         String home_phone,
         String mobile_phone,
         String work_phone,
         String fax,
         String email,
         String email_2,
         String email_3,
         String homepage,
         Integer birthdayDay,
         String birthdayMonth,
         String birthdayYear,
         Integer anniversaryDay,
         String anniversaryMonth,
         String anniversaryYear) {
    public ContactData() {
        this("","","","","","","","","","","","","","","","","",0,"-","",0,"-","");
    }

    public ContactData withId(String id) {
        return new ContactData(
                id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withFirstName(String first_name) {
        return new ContactData(
                this.id,
                first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withMiddleName(String middle_name) {
        return new ContactData(
                this.id,
                this.first_name,
                middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withLastName(String last_name) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withNickname(String nickname) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withPhoto(String photo) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withTitle(String title) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withCompany(String company) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withAddress(String address) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withHomePhone(String home_phone) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withMobilePhone(String mobile_phone) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withWorkPhone(String work_phone) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withFax(String fax) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withEmail(String email) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withEmail2(String email_2) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withEmail3(String email_3) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withHomePage(String homepage) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withBirthday(Integer birthdayDay, String birthdayMonth, String birthdayYear) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                birthdayDay,
                birthdayMonth,
                birthdayYear,
                this.anniversaryDay,
                this.anniversaryMonth,
                this.anniversaryYear);
    }

    public ContactData withAnniversary(Integer anniversaryDay, String anniversaryMonth, String anniversaryYear) {
        return new ContactData(
                this.id,
                this.first_name,
                this.middle_name,
                this.last_name,
                this.nickname,
                this.photo,
                this.title,
                this.company,
                this.address,
                this.home_phone,
                this.mobile_phone,
                this.work_phone,
                this.fax,
                this.email,
                this.email_2,
                this.email_3,
                this.homepage,
                this.birthdayDay,
                this.birthdayMonth,
                this.birthdayYear,
                anniversaryDay,
                anniversaryMonth,
                anniversaryYear);
    }

}
